### ISSUE TITLE
Crashing on startup Windows 10

### ISSUE THREAD

**Issue by souptik-samanta** [hackclub/kicad-wakatime#13]
OS: Windows

Magic word:dreadnought

When trying to open the extension for windows its opening for a fraction of second and then closing
so its crashing 
No logs
no screenshots as i cannot even see the app just a black screen pops and turns off

**Comment by sporeball** [comment]
using a pre-release build, this crash was isolated to the file watcher; any errors there should now propagate instead of crashing the plugin.

closing this issue; please verify that you have selected the same folder in KiCAD as the one you are tracking in kicad-wakatime, and DM me on Slack if you are still unable to send heartbeats.
